### PR TITLE
Remove warnings in financial example

### PR DESCRIPTION
**Pull request by qbarthelemy**
Remove warnings in financial example #195 

Please wait for the build check in the doc before merging @gcattan

### CODE REVIEW

**Comment by gcattan** [comment]
Thanks @qbarthelemy ! May be we can exclude this example from CI as it is very long to run. Or cache the results so we skip some computation on the Github action.

**Comment by user12345678901** [comment]
I cannot edit your branch, but we likely need to edit the Dockerfile and change the protobuf version from 4.25.0 to 4.25.1

**Comment by gcattan** [comment]
Can you try changing protobuf version from 4.25.0 to 4.25.1?

**Comment by gcattan** [comment]
Do not take into account my last message, it seems I can edit the Dockerfile myself.

**Comment by user12345678901** [comment]
Everything looks ok to me: 

image

Thank you for the changes @qbarthelemy !

**Review by user12345678901 — APPROVED** [review]

**Comment by gcattan** [comment]
Everything looks ok to me: 

image

Thank you for the changes @qbarthelemy !

**Comment by qbarthelemy** [comment]
It's ok for me to merge.

But, it seems that sometimes, the set of predictions by QSVM with y=1 is empty, raising an error
https://github.com/pyRiemann/pyRiemann-qiskit/actions/runs/6889981977/job/18742076015#step:5:1813

**Pull request merged**
