### PR TITLE
Complete read the doc file

### PR DESCRIPTION
**Pull request by qbarthelemy**
See https://github.com/pyRiemann/pyRiemann/blob/master/.readthedocs.yaml

### CODE REVIEW

**Review by gcattan — APPROVED** [review]
Thx @qbarthelemy!

**Comment by qbarthelemy** [comment]
There is still an error in doc, see
```
Unexpected failing examples:
/github/workspace/examples/other_datasets/plot_tutorial_quantum_svm_titanic_data.py failed leaving traceback:
Traceback (most recent call last):
  File "/github/workspace/examples/other_datasets/plot_tutorial_quantum_svm_titanic_data.py", line 122, in <module>
    sns.catplot(
  File "/usr/local/lib/python3.9/site-packages/seaborn/categorical.py", line 3244, in catplot
    g.map_dataframe(plot_func, x=x, y=y, hue=hue, **plot_kws)
  File "/usr/local/lib/python3.9/site-packages/seaborn/axisgrid.py", line 819, in map_dataframe
    self._facet_plot(func, ax, args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/seaborn/axisgrid.py", line 848, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "/usr/local/lib/python3.9/site-packages/seaborn/categorical.py", line 2955, in countplot
    plotter.plot(ax, kwargs)
  File "/usr/local/lib/python3.9/site-packages/seaborn/categorical.py", line 1587, in plot
    self.annotate_axes(ax)
  File "/usr/local/lib/python3.9/site-packages/seaborn/categorical.py", line 767, in annotate_axes
    ax.legend(loc="best", title=self.hue_title)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 322, in legend
    handles, labels, kwargs = mlegend._parse_legend_args([self], *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/legend.py", line 1361, in _parse_legend_args
    handles, labels = _get_legend_handles_labels(axs, handlers)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/legend.py", line 1291, in _get_legend_handles_labels
    if label and not label.startswith('_'):
AttributeError: 'numpy.int64' object has no attribute 'startswith'
```

**Comment by gcattan** [comment]
Hm. could be that the version of seaborn is not compatible with numpy.

**Comment by gcattan** [comment]
This or MOABB ^^
image

**Pull request merged**
