### PR TITLE
Create python-publish.yml

### PR DESCRIPTION
**Pull request by gcattan**
@qbarthelemy @sylvchev @toncho11 I think there is enough material to publish version 0.0.3dev.
I suggest we put the package also on Pypi if this works for you.

### CODE REVIEW

**Comment by qbarthelemy** [comment]
Ok for me to publish 0.0.2 and to open 0.0.3-dev.

**Comment by qbarthelemy** [comment]
Published versions should not contain "dev" in their names.
https://pyriemann-qiskit.readthedocs.io/en/latest/whatsnew.html

**Comment by gcattan** [comment]
Thanks for spotting the incoherence :)

**Comment by toncho11** [comment]
It should be 0.3, not 0.4?

**Comment by gcattan** [comment]
I forgot to update the version after release v0.0.2.
Since we are releasing v0.0.3, I think we are now opening v0.0.4-dev.

**Comment by gcattan** [comment]
@toncho11 definitely not awake today. Thanks ^^

**Pull request merged**
