### PR TITLE
docplex optimizers

### PR DESCRIPTION
**Pull request by gcattan**
Follow up for #28 

This PR introduces one classical and one naive quantum optimizer, as per comment https://github.com/pyRiemann/pyRiemann-qiskit/pull/56#issuecomment-1164225183
It also bump the version of docplex and add a new dependency to qiskit_optimization.

### CODE REVIEW

**Comment by toncho11** [comment]
I am looking into the test program. 

1) It looks like a docplex problem is specified with "test_get_square_cont_var", but then the optimizer is created without providing this docplex model? 
2) Can we also call "solve()" on the two optimizers (quantum and classical) and validate that a result has been returned? Or it is too early for that?

**Comment by gcattan** [comment]
Hi, 

I have added comments to "test_get_square_cont_var", I hope it is more clear.

As for the functional tests of the solve method of the optimizers themselves, I would prefer to do it along with #26 to reuse the docplex method that would be defined in #26. What do you think?

**Comment by toncho11** [comment]
Maybe you can add a general description of "docplex.py " such as:
"This module contains both classic and quantum optimizers. The quantum optimizer allows an optimization problem with constraints (in the form of docplex model) to be run on a quantum computers. "

**Comment by gcattan** [comment]
Thx for the review @toncho11 :)

**Pull request merged**
