### PR TITLE
Gc/fix token incorrect with rg default pipeline

### PR DESCRIPTION
**Pull request by gcattan**
@toncho11 FYI

Implements:

- https://github.com/pyRiemann/pyRiemann-qiskit/issues/40
- https://github.com/pyRiemann/pyRiemann-qiskit/issues/45

### CODE REVIEW

**Comment by toncho11** [comment]
Hi,

The __init__ of the QuanticClassifierBase is executed twice and the second time q_account_token is empty.

**Comment by toncho11** [comment]
It also says "TypeError: __init__() got an unexpected keyword argument 'q_account_token'"

**Comment by toncho11** [comment]
Yes, it works. The correct usage is now:

`params={"q_account_token": "load_account"}`

**Comment by gcattan** [comment]
Thanks for testing! @qbarthelemy fee free to review when you have time :)

**Pull request merged**
