### PR TITLE
Adjusting the parameters for QuantumMDM (class and pipeline)

### PR DESCRIPTION
**Pull request by toncho11**
This is PR is part of https://github.com/pyRiemann/pyRiemann-qiskit/issues/156

- Removing un unused parameter "gen_feature_map" for QuantumMDM
- Adding a new parameter "upper_bound" for QuantumMDM

### CODE REVIEW

**Comment by gcattan** [comment]
Thanks @toncho11 ! Feel free to merge when you are ready

**Review by gcattan — APPROVED** [review]

**Comment by toncho11** [comment]
There is some kind of problem. It prevents classify_P300_bi_quantum_mdm.py from completing.

```
 File "C:\Work\PythonCode\pyRiemann-qiskit\pyq_env\Lib\site-packages\docplex\mp\mfactory.py", line 362, in _expand_bounds
    fn_bounds = [var_bound(k) for k in keys]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\PythonCode\pyRiemann-qiskit\pyq_env\Lib\site-packages\docplex\mp\mfactory.py", line 362, in <listcomp>
    fn_bounds = [var_bound(k) for k in keys]
                 ^^^^^^^^^^^^
  File "C:\Work\PythonCode\pyRiemann-qiskit\pyq_env\Lib\site-packages\pyriemann_qiskit\utils\hyper_params_factory.py", line 132, in <lambda>
    return lambda n_features: ZZFeatureMap(
                              ^^^^^^^^^^^^^
  File "C:\Work\PythonCode\pyRiemann-qiskit\pyq_env\Lib\site-packages\qiskit\circuit\library\data_preparation\zz_feature_map.py", line 99, in __init__
    if feature_dimension < 2:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'tuple' and 'int'
```

It a feature map function is always assigned in the base class even if not needed.

**Comment by gcattan** [comment]
Ok, I see. There are some leftovers in the `pipelines.py` script for QuantumMDM pipelines.
Can you try to replace them with the upper-bound coefficient?

**Comment by gcattan** [comment]
Sorry, it am mistaking. My precedent comment does not apply.

**Comment by toncho11** [comment]
It seems the problem is in the voting classifier. It still sets "gen_feature_map" for QuantumMDMWithRiemannianPipeline while this is indeed the "upper_bound" parameter now.

**Pull request merged**
