### PR TITLE
Add a new benchmark over many datasets

### PR DESCRIPTION
**Pull request by toncho11**
It does include many P300 and Motor Imagery datasets. 
It adapts both the paradigms and the pipelines. 
And most importantly it runs statistics to show if the results are significant (using moabb).

The initial version can be run already. 

Currently it requires the latest version of MOABB from github where:
    - `cache_config` parameter is availabe for WithinSessionEvaluation()
    - this bug is fixed: https://github.com/NeuroTechX/moabb/issues/514

### CODE REVIEW

**Comment by gcattan** [comment]
@toncho11 Do you want to update up-merge your branch and update your code with the latest changes? I could reuse this pipeline also to benchmark the NCH.

**Comment by toncho11** [comment]
But this benchmark requires the latest version of MOABB from git.

**Comment by toncho11** [comment]
I mean after MOABB 1.1.0.

**Comment by toncho11** [comment]
```
install_requires = [
        'moabb @ git+ssh://git@github.com//NeuroTechX/moabb.git'
    ]
```

**Pull request merged**
