### PR TITLE
allow cov_to_corr_matrix to process multiple matrices at once

### PR DESCRIPTION
**Pull request by qbarthelemy**

### CODE REVIEW

**Comment by qbarthelemy** [comment]
It would also be possible to depreciate `cov_to_corr_matrix`.

**Comment by gcattan** [comment]
Yes, it could be redundant with pyRiemann `normalize` function, but `cov_to_corr_matrix` is also more specific. 
I leave it up to you :)

We will need the changes in the docker file for the ci/cd to pass:

image

**Comment by qbarthelemy** [comment]
Branch is rebased, but docker CI failed.

**Review by gcattan — APPROVED** [review]

**Comment by gcattan** [comment]
Thanks @qbarthelemy!

**Pull request merged**
