### PR TITLE
Abstract for JOSS journal

### PR DESCRIPTION
**Pull request by gcattan**
The full JOSS recommendation are [here](https://joss.readthedocs.io/en/latest/submitting.html). Below, the summary:

image

The compiled PDF version is downloadable as an artifact [here](https://github.com/gcattan/pyRiemann-qiskit/actions/workflows/draft-pdf.yml).

### CODE REVIEW

**Comment by gcattan** [comment]
@toncho11 I have updated the paper with the latest text from the wiki. Please, review when you have time.

**Comment by gcattan** [comment]
@toncho11 will have little time to work on this abstract. @qbarthelemy or @sylvchev will you be available to review this?

**Comment by qbarthelemy** [comment]
It's a good idea, but I think that we should publish pyRiemann before. @sylvchev @plcrodrigues @agramfort

**Comment by plcrodrigues** [comment]
> It's a good idea, but I think that we should publish pyRiemann before. @sylvchev @plcrodrigues @agramfort

Agreed.

**Comment by toncho11** [comment]
I am not sure. How much time will take to publish pyRiemann? This risks blocking pyRiemann-Qiskit for a very long time.

**Comment by agramfort** [comment]
We should consider publishing a JOSS paper on pyRiemann yes. To cite pyRiemann in this paper we can use a zenodo DOI but I am moderately convinced it's useful in the long run.

**Comment by gcattan** [comment]
Once pyRiemann is published on JoSS, I think we still have time to update the reference to it in this paper. pyRiemann-qiskit is not as mature as pyRiemann and I think it will take some time before it gets published. This is why it may be a good idea to start the process soon, what do you think ? 

Side question: do you want me to prepare the workflow in pyRiemann repo ?

**Comment by gcattan** [comment]
Hello. Did you have some time to think about it?

**Comment by agramfort** [comment]
I asked @alexandrebarachant to have access to zenodo. I don't see anything
happening very soon on pyRiemann otherwise

**Comment by sylvchev** [comment]
Yes, I have a draft for Pyriemann targeting https://jmlr.org/mloss/ that I need to reorganize before sharing. It will happen soon!

**Comment by gcattan** [comment]
Ok, thank you for the update. I will wait for Zenodo DOI and pyRiemann draft to be ready then.
Please, also have a look to this abstract when you have time.

**Comment by agramfort** [comment]
let's discuss the target journal to maximize our chances and be in the
right scope.

Sylvain call me ok?

**Comment by agramfort** [comment]
a few things for me need to be decided first:
- who is onboard? One solution is to add to the paper anyone who
contributed in the past but this deserves some discussion I guess.
- who is leading this? First author? Senior Author?

feel free to voice your opinion

**Comment by plcrodrigues** [comment]
> a few things for me need to be decided first: - who is onboard? One solution is to add to the paper anyone who contributed in the past but this deserves some discussion I guess. - who is leading this? First author? Senior Author? feel free to voice your opinion

How did you guys do for `sklearn` ? We have 21 contributors on `pyriemann` so far, so it could maybe be reasonable to try contacting each person to ask if they want to participate in the paper ? (and ask for some help ?)

**Comment by agramfort** [comment]
since the last zenodo entry I would say it's me and Quentin mostly who
arrived in the game no?

**Comment by qbarthelemy** [comment]
I would have kept the first seven contributors.
Maybe we should have this discussion on pyRiemann : https://github.com/pyRiemann/pyRiemann/issues/203

**Comment by gcattan** [comment]
Hi, do you have some update with the pyriemann paper? If no, I have referenced the Zenodo DOI of pyRiemann so we could start the submission.

**Comment by agramfort** [comment]
@gcattan you can now refer to PyRiemann with this bibtex

https://github.com/pyRiemann/pyRiemann/blob/master/README.md#how-to-cite

**Pull request merged**
